//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Entity_Proje
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_Admin
    {
        public byte adminId { get; set; }
        public string adminSifre { get; set; }
        public string adminAd { get; set; }
    }
}
